<!-- Inicia Menu -->
<ul class="accordion" id="accordion-1">
 <?php foreach($menu as  $c): ?>
    <!-- Procesa las Categorias -->
    <li>
        <a href='#'><?php echo $c['titulo_categoria']; ?></a>
        <ul>
        <!-- Procesa los menus -->
        <?php foreach($c['menus'] as  $m): ?>
            <?php if (count($m['permisos'])==1):?>
                <?php foreach($m['permisos'] as  $p): ?>
                    <li>
                        <a href='<?php echo $p['enlace']; ?>'><?php echo $p['titulo_permiso']; ?></a>
                    </li>
                <?php endforeach; ?>
            <?php else: ?>
                <li>
                    <a href='#'><?php echo $m['titulo_menu']; ?></a>
                    <!-- Procesa los permisos -->
                    <ul>
                    <?php foreach($m['permisos'] as  $p): ?>
                        <?php if (count($p['parametros'])==1):?>
                            <?php foreach($p['parametros'] as  $t): ?>
                                <li>
                                    <a href='<?php echo $t['enlace']; ?>'><?php echo $p['titulo_permiso']; ?></a>
                                </li>
                            <?php endforeach; ?>
                        <?php elseif(count($p['parametros'])==0): ?>
                            <li>
                                <a href='<?php echo $p['enlace']; ?>'><?php echo $p['titulo_permiso']; ?></a>
                            </li>   
                        <?php else: ?>
                            <li>
                                <a href='#'><?php echo $p['titulo_permiso']; ?></a>
                                <!-- Procesa los parametros -->
                                <ul>
                                   <?php foreach($p['parametros'] as  $t): ?>
                                        <li>
                                            <a href='<?php echo $t['enlace']; ?>'><?php echo $t['titulo_parametro']; ?></a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                             </li>
                        <?php endif; ?>    
                    <?php endforeach; ?>
                    </ul>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
    </li>
 <?php endforeach; ?>   
</ul>
