     <!-- Encabezado -->
     <div id="encabezado">
            	<div id="ie_header">
        	</div>
                <div id="degradado0">
                </div>
                <!--<canvas id="degradado">
                </canvas>
                <script type="text/javascript">
                    var c=document.getElementById("degradado");
                    var cxt=c.getContext("2d");
                    
                    var grd=cxt.createLinearGradient(0,150,0,0);
                    
                    grd.addColorStop(0,"transparent");
                    //grd.addColorStop(0.5,"green");
                    grd.addColorStop(0.25,"red");
                    
                    cxt.fillStyle=grd;
                    cxt.fillRect(0,0,1600,150);
                </script>-->
         <!-- Nombre de la aplicación -->   
                <nav>
                    <div id="menu_icon">
                        <img id="menu_img" src="<?=$menu['ruta_img']?>menu_318.png">
                        <img  style="height: 0px; width: 23px;" id="invisible2" src="<?=$menu['ruta_img']?>c-invisible.png">
                    </div>
                    <div id="aplicacion" href="<?=BASE_URL?>">
                        <p id="nom"><?=APP_NAME?></p>
                        <p id="version">Version 1.0</p>
                    </div>
                    <div class="dropper">&raquo;</div>
                    
               <!-- Menu Principal -->
                    <div class="nav-collapse" id="menu_p">
                        <div id="menu_show"></div>
                    </div>
                </nav>
               <!-- Indentificador de CETPRO -->
                <div id="logotipo">
                    <!--<div id="membrete">-->
                        <img id="logo" src="<?=$menu['ruta_img']?>san_luis.png">
                        <!--<div id="tipo"><?=$menu['cetpro']?></div>-->
                    <!--</div>-->
                </div>
                <!-- Identificador de usuario -->
                <div class="usuario">
                    <div id="data_user">
                        <div id="pre-foto">
                            <div id="foto">
                                <img src="<?=$menu['ruta_img']?>male.jpg">
                            </div>
                        </div>
                        <ul id="datos"> <!-- Menu usuario -->
                            <li>
                                <a href="#">
                                    <div id="data">
                                        <?=$menu['usuario']?><br>
                                        <span style="font-weight:bold"><?=$menu['role']?></span><br>
                                        <!-- Invisible 2 aqui -->   
                                    </div>
                                    <div class="dropper">&raquo;</div>
                                    <ul class="menucito"> <!-- SubMenu usuario -->
                                       <li><a href="<? BASE_URL ?>usuarios/cerrar">Cerrar Sesion</a></li>
                                       <li><a href="#">Config</a>
                                           <ul>
                                               <li><a href="#">Sittings</a></li>
                                               <li><a href="#">Values</a></li>
                                           </ul>
                                       </li>
                                       <li><a id="tempo" href="#">Tempo</a></li>
                                    </ul>
                                 </a>
                                 <img id="invisible2" src="<?=$menu['ruta_img']?>c-invisible.png">
                            </li>
                        </ul>
                    </div>
                </div>
         </div>